# Generated by Django 5.0.6 on 2024-06-24 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_handler', '0003_alter_pricerecord_record_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricerecord',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oauth_handler.brand'),
        ),
    ]
