# Generated by Django 5.0.6 on 2024-06-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_handler', '0004_pricerecord_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price_default',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='item',
            name='price_msrp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='item',
            name='price_online',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
